---
title: "Corona Worst-Day Lineplots"
author: "Cedric Scherer"
date: "13th of April 2020"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
Sys.setlocale("LC_TIME", "C")
```


## Setup
  
```{r prep}
library(tidyverse)
library(lubridate)
library(gghighlight)
library(ggtext)
library(pdftools)
library(showtext)

font_add_google("Open Sans", "Open Sans")
font_add_google("Overpass", "Overpass")
font_add_google("Overpass Mono", "Overpass Mono")

theme_set(theme_minimal(base_size = 16, base_family = "Open Sans"))
theme_update(axis.ticks = element_blank(),
             axis.title.x = element_text(size = 18, face = "bold", color = "grey40",
                                         margin = margin(t = 15), hjust = .25),
             axis.title.y = element_text(size = 18, face = "bold", color = "grey40", 
                                         margin = margin(r = 15)),
             axis.text = element_text(family = "Overpass"),
             axis.text.x = element_text(size = 14),
             axis.text.y = element_text(margin = margin(r = 15)),
             panel.grid.minor = element_blank(),
             panel.grid.major.x = element_blank(),
             panel.grid.major.y = element_line(size = .35),
             panel.spacing.x = unit(.4, "lines"),
             panel.spacing.y = unit(1.2, "lines"),
             strip.text = element_text(family = "Overpass", size = 18, face = "bold"),
             plot.title = element_markdown(family = "Overpass", size = 42, face = "bold",
                                           color = "black", hjust = 0, lineheight = 1.05,
                                           margin = margin(15, 0, 25, 0)),
             plot.title.position = "plot",
             plot.subtitle = element_markdown(size = 21, color = "grey20", hjust = 0, 
                                              lineheight = 1.15, margin = margin(0, 0, 35, 0)),
             plot.caption = element_markdown(size = 14, color = "grey20", hjust = 1, 
                                             margin = margin(35, 0, 0, 0)),
             plot.margin = margin(20, 30, 20, 30))
```


## Data Preparation

```{r data}
## download atest data
df_corona <- readr::read_csv("https://datahub.io/core/covid-19/r/time-series-19-covid-combined.csv")

## deaths per day with clean column names, dates and country names 
df_corona_days <-
  df_corona %>% 
  dplyr::select(
    date = Date,
    country = `Country/Region`,
    state = `Province/State`,
    deaths = Deaths
  ) %>% 
  group_by(country, date) %>% 
  summarize(deaths = sum(deaths, na.rm = T)) %>% 
  group_by(country) %>%
  mutate(
    yday = yday(date),
    day = day(date),
    month = month(date, label = T)
  ) %>% 
  arrange(country, yday) %>% 
  mutate(
    daily = deaths - lag(deaths),
    daily = if_else(is.na(daily), deaths, daily)
  ) %>% 
  ungroup() %>% 
  filter(yday >= min(yday[which(daily > 0)])) %>% 
  mutate(
    daily = if_else(daily <= 0, NA_real_, daily),
    country = case_when(
      country == "US" ~ "United States",
      country == "Korea, South" ~ "South Korea",
      country == "Bosnia and Herzegovina" ~ "Bosnia–Herzegovina",
      #country == "China" ~ "China*",
      TRUE ~ country
    ),
    country = str_replace(country, " and ", " & ")
  )

## summary of confirmed deaths worldwide
df_corona_world <-
  df_corona_days %>% 
  group_by(date, yday, day, month) %>% 
  summarize_at(
    vars(c("deaths", "daily")), sum, na.rm = T
  ) %>% 
  filter(daily > 0) %>% 
  mutate(country = "Worldwide")

## calculate rolling average and add label column
df_corona_g <- 
  df_corona_days %>% 
  bind_rows(df_corona_world) %>% 
  group_by(country) %>% 
  mutate(
    daily = if_else(is.na(daily), 0, daily),
    roll = rollmean(daily, 7, align = "left", fill = NA),
    max = max(roll, na.rm = T),
    rel = roll / max,
    rel = if_else(is.na(rel), 0, rel),
    sum = sum(daily, na.rm = T),
    day_first = min(yday[which(rel > 0)]),
    day_rel = yday - day_first
  ) %>% 
  filter(yday < max(yday) - 5, day_rel >= 0) %>% 
  mutate(
    day_max = max(yday[which(rel == 1)]),
    latest = daily[which(yday == max(yday))],
    lab_sum = format(sum, big.mark = ","),
    lab_latest = format(latest, big.mark = ",")
  ) %>% 
  ungroup()

latest_day <- max(df_corona_g$yday)
latest_rel <- max(df_corona_g$day_rel)
```

```{r facets-plot, fig.width = 27.5, fig.height = 20}
## only countries with more than 50 or more confirmed deaths
dff <- 
  df_corona_g %>% 
  filter(
    sum >= 50, 
    country != "Worldwide"
  ) %>% 
  mutate(country = factor(country)) %>% 
  mutate(lab_sum = if_else(as.numeric(country) == 1, 
                             glue::glue("Total: {lab_sum}"),
                             lab_sum))

f <- 
  ggplot(dff, 
         aes(day_rel, rel, 
             group = country)) +
    geom_line(alpha = .35,
              size = .7) +
    geom_point(data = dff %>% filter(yday == latest_day),
               alpha = 1,
               size = 1) +
    gghighlight(use_direct_label = F,
                unhighlighted_params = list(color = "grey80")) +
    coord_cartesian(clip = "off") +
    scale_x_continuous(expand = c(0, 0),
                       limits = c(-10, latest_rel + 11),
                       breaks = seq(0, 75, by = 25)) + 
    scale_y_continuous(expand = c(.003, .003),
                       limits = c(0, 1.05),
                       labels = scales::percent_format()) +
    facet_wrap(~ country, ncol = 8)

f + 
  geom_line(size = 1.4, color = "grey20") +
  geom_point(data = dff %>% filter(rel == 1),
             size = 2,
             color = "#e15383") +
  geom_point(data = dff %>% filter(yday == latest_day),
             size = 4.5,
             shape = 21,
             color = "white",
             fill = "black",
             stroke = .6) + #278f84
  geom_point(data = dff %>% filter(yday == latest_day),
             aes(color = rel),
             size = 2) +
  # geom_point(data = dff %>% filter(rel == 1 & yday == latest_day),
  #            size = 2,
  #            color = "#c93a6e") +
  geom_rect(xmin = -Inf, xmax = 0,
              ymin = -Inf, ymax = Inf,
              fill = "white",
              inherit.aes = F) +
  geom_rect(xmin = latest_rel + 2.5, xmax = Inf,
              ymin = -Inf, ymax = Inf,
              fill = "white",
              inherit.aes = F) +
  ## version with label showing latest daily numbers
  geom_label(data = dff %>% filter(yday == latest_day & country != "China"),
            aes(label = lab_sum),
            size = 5,
            family = "Overpass",
            color = "grey20",
            fontface = "bold",
            hjust = 0,
            nudge_x = 4,
            lineheight = .9) +
  geom_label(data = dff %>% filter(yday == latest_day & country == "China"),
            aes(label = lab_sum),
            size = 5,
            family = "Overpass",
            color = "grey20",
            fontface = "bold",
            vjust = 0,
            nudge_y = .075) +
  ## version with sum labels in rightupper corner
  # geom_label(data = dff %>% filter(yday == latest_day),
  #            aes(x = latest_rel + 10, y = .87, label = lab),
  #            size = 4.5,
  #            family = "Overpass",
  #            color = "grey20",
  #            fontface = "bold",
  #            hjust = 1) +
  geom_text(data = dff %>% filter(day_rel == 0),
            aes(label = glue::glue("{month} {day}")),
            size = 4,
            family = "Overpass",
            color = "grey20",
            fontface = "bold",
            hjust = 1,
            vjust = .5,
            nudge_x = -1) +
  rcartocolor::scale_color_carto_c(palette = "PinkYl", guide = F) +
  labs(x = "Number of days since first confirmed death due to COVID-19",
       y = "COVID-19 death cases relative to each country's highest average daily death toll so far", 
       title = "<b style='color:#c93a6e;'>The Worst Days:</b> Peaks in Confirmed Daily Deaths Due to COVID-19 So Far",
       subtitle = "<b>Each panel shows the trajectory of confirmed deaths due to COVID-19 as percentage of daily deaths relative to the <i style='color:#c93a6e;'>worst day so far</i> for countries with at least 50 reported deaths.</b><span style='font-size:16pt;'><br><br>For each day, starting with the date of first reported death, the 7-day rolling average of confimed deaths per day is divided by the <b style='color:#c93a6e;'>highest average number of daily deaths so far defined as 100%</b>.<br>The text labels show the day of the first cofirmed death due to COIVD-19 and the overall death toll per country.</span>",
       caption = "**Visualization: Cédric Scherer  •  Data: Johns Hopkins University Center for Systems Science and Engineering (CSSE) via datahub.io**<br>Note: Charts contain all confirmed deaths due to COVID-19 since January 22<sup>nd</sup> to April 13<sup>th</sup> 2020 for countries with 50 or more deaths.")

ggsave(here::here("plots", "corona_line_facet.pdf"),
       width = 27.5, height = 20, device = cairo_pdf)

setwd(here::here("plots"))
pdf_convert(pdf = here::here("plots", "corona_line_facet.pdf"), 
              format = "png", dpi = 750)
```
