---
title: "Corona Worst-Day Trajectories"
author: "Cedric Scherer"
date: "13th of April 2020"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
Sys.setlocale("LC_TIME", "C")
```


## Setup
  
```{r prep}
library(tidyverse)
library(lubridate)
library(zoo)
library(gghighlight)
library(ggtext)
library(pdftools)
library(showtext)

font_add_google("Open Sans", "Open Sans")
font_add_google("Overpass", "Overpass")
font_add_google("Overpass Mono", "Overpass Mono")

showtext_auto()

theme_set(theme_minimal(base_size = 16, base_family = "Open Sans"))
theme_update(axis.ticks = element_blank(),
             axis.title.x = element_text(size = 18, face = "bold", color = "grey40",
                                         margin = margin(t = 15)),
             axis.title.y = element_text(size = 18, face = "bold", color = "grey40", 
                                         margin = margin(r = 15)),
             axis.text = element_text(family = "Overpass"),
             axis.text.x = element_text(size = 14),
             axis.text.y = element_text(margin = margin(r = 15)),
             panel.grid.minor = element_blank(),
             panel.grid.major.x = element_blank(),
             panel.grid.major.y = element_line(size = .35),
             panel.spacing.x = unit(.4, "lines"),
             panel.spacing.y = unit(1.2, "lines"),
             strip.text = element_text(family = "Overpass", size = 18, face = "bold"),
             plot.title = element_markdown(family = "Overpass", size = 46, face = "bold",
                                           color = "black", hjust = 0, lineheight = 1.05,
                                           margin = margin(15, 0, 25, 0)),
             plot.title.position = "plot",
             plot.subtitle = element_markdown(size = 22, color = "grey20", hjust = 0, 
                                              lineheight = 1.15, margin = margin(0, 0, 35, 0)),
             plot.caption = element_markdown(size = 16, color = "grey20", hjust = 1, 
                                             lineheight = 1.05, margin = margin(40, 0, 0, 0)),
             plot.margin = margin(20, 30, 20, 30))
```


## Data Preparation

```{r data}
## download atest data
df_corona <- readr::read_csv("https://datahub.io/core/covid-19/r/time-series-19-covid-combined.csv")

## deaths per day with clean column names, dates and country names 
df_corona_days <-
  df_corona %>% 
  dplyr::select(
    date = Date,
    country = `Country/Region`,
    state = `Province/State`,
    deaths = Deaths
  ) %>% 
  group_by(country, date) %>% 
  summarize(deaths = sum(deaths, na.rm = T)) %>% 
  group_by(country) %>%
  mutate(
    yday = yday(date),
    day = day(date),
    month = month(date, label = T)
  ) %>% 
  arrange(country, yday) %>% 
  mutate(
    daily = deaths - lag(deaths),
    daily = if_else(is.na(daily), deaths, daily)
  ) %>% 
  ungroup() %>% 
  filter(yday >= min(yday[which(daily > 0)]) - 6) %>% 
  mutate(
    #daily = if_else(daily <= 0, NA_real_, daily),
    country = case_when(
      country == "US" ~ "United States",
      country == "Korea, South" ~ "South Korea",
      country == "Bosnia and Herzegovina" ~ "Bosnia–Herzegovina",
      country == "China" ~ "China*",
      country == "Congo (Kinshasa)" ~ "DR Congo",
      country == "Congo (Brazzaville)" ~ "Congo-Brazzaville",
      TRUE ~ country
    ),
    country = str_replace(country, " and ", " & ")
  )

## summary of confirmed deaths worldwide
df_corona_world <-
  df_corona_days %>% 
  group_by(date, yday, day, month) %>% 
  summarize_at(
    vars(c("deaths", "daily")), sum, na.rm = T
  ) %>% 
  filter(daily > 0) %>% 
  mutate(country = "Worldwide")

## add days before first death in China to calculate rolling avg
df_corona_china_zeros <-
  df_corona_days %>% 
  filter(country == "China*") %>% 
  slice(1:6) %>% 
  mutate(
    date = date - 6,
    deaths = 17,
    yday = yday(date),
    day = day(date),
    month = month(date, label = T),
    daily = 0
  )

## fix deaths in Wuhan, China, that were reported late
china_deaths <- 
  df_corona_days %>% 
  filter(country == "China*" & yday == 108) %>% ## April 17th
  pull(daily)

df_corona_china_fix <-
  df_corona_days %>% 
  filter(country == "China*" & yday <= 108) %>% 
  mutate(
    daily = if_else(yday == 108, 0, daily),
    daily = daily + round(daily * china_deaths / sum(daily)),
    daily = if_else(daily == max(daily), daily - 3, daily)
  ) 


## calculate rolling average and add label column
df_corona_roll <- 
  df_corona_days %>% 
  filter(!(country == "China*" & yday <= 108)) %>% 
  bind_rows(df_corona_world) %>% 
  bind_rows(df_corona_china_zeros) %>% 
  bind_rows(df_corona_china_fix) %>% 
  arrange(country, date) %>% 
  group_by(country) %>% 
  mutate(
    #daily = if_else(is.na(daily), 0, daily),
    roll = rollmean(daily, 7, align = "right", fill = NA),
    max = max(roll, na.rm = T),
    rel = roll / max,
    rel = if_else(is.na(rel), 0, rel),
    rel = if_else(rel < 0, 0, rel),
    sum = sum(daily, na.rm = T),
    day_first = min(yday[which(rel > 0)]),
    day_rel = yday - day_first
  ) %>% 
  filter(day_rel >= 0) %>%   ##yday < max(yday) - 5, 
  mutate(
    day_max = max(yday[which(rel == 1)]),
    latest = daily[which(yday == max(yday))],
    lab_sum = format(sum, big.mark = ","),
    lab_latest = format(latest, big.mark = ",")
  ) %>% 
  ungroup()

first_day <- min(df_corona_roll$yday)
latest_day <- max(df_corona_roll$yday)
latest_rel <- max(df_corona_roll$day_rel)

fig_width = 29
fig_height = 26.5

subtitle_lab <- "<b>Each panel shows the trajectory of confirmed deaths due to COVID-19 as percentage of daily deaths relative to the <i style='color:#c93a6e;'>worst day so far</i> for countries with at least 100 reported deaths.</b><span style='font-size:18pt;'><br><br>For each day, starting with the date of first reported death, the 7-day rolling average of confimed deaths per day is divided by the <b style='color:#c93a6e;'>highest average number of daily deaths so far defined as 100%</b>.<br>The text labels show the day of the first cofirmed death due to COVID-19 and the overall death toll per country.</span>"

caption_lab <- "Note: Charts contain all confirmed deaths due to COVID-19 from January 22<sup>nd</sup> to May 28<sup>th</sup> 2020 for countries with 100 or more deaths.<br>* The deaths reported on April 17<sup>th</sup> in Wuhan, China, have been added proportionally to the confirmed daily deaths until that date.<br><br>**Visualization: Cédric Scherer  •  Data: Johns Hopkins University Center for Systems Science and Engineering (CSSE) via datahub.io**"

label_col <- colorspace::darken(c("#f2eaa8", "#ffd08e", "#ffa679", "#f67b77", "#e15383"), .05, space = "HLS")
```



## Facets: Trajectories per Country

```{r facets-plot, fig.width = fig_width, fig.height = fig_height}
## only countries with more than 100 or more confirmed deaths
dff <- 
  df_corona_roll %>% 
  filter(
    sum >= 100, 
    country != "Worldwide"
  ) %>% 
  mutate(country = factor(country)) %>% 
  mutate(lab_sum = if_else(as.numeric(country) == 1, 
                           glue::glue("Total: {lab_sum}"),
                           lab_sum)) %>% 
  group_by(country) %>% 
  mutate(
    # lab_worst = if_else(as.numeric(country) == 1, 
    #                     "Maximum daily\naverage so far", 
    #                     NA_character_),
    # xend = if_else(as.numeric(country) == 1, day_rel + 35, NA_real_),
    # yend = if_else(as.numeric(country) == 1, .825, NA_real_)
    lab_worst = if_else(country == "Algeria", 
                        "Maximum daily\naverage so far", 
                        NA_character_),
    xend = if_else(country == "Algeria", day_rel + 40, NA_real_),
    yend = if_else(country == "Algeria", .825, NA_real_)
  )

f <- 
  ggplot(dff, 
         aes(day_rel, rel, 
             group = country)) +
    ## all trajectories
    geom_line(alpha = .1,
              size = .7) +
    ## all worst days as dots
    geom_point(data = dff %>% filter(yday == latest_day),
               alpha = 1,
               size = 1) +
    gghighlight(use_direct_label = F,
                unhighlighted_params = list(color = "grey70")) +
    facet_wrap(~ country, ncol = 8) +
    coord_cartesian(clip = "off") +
    scale_x_continuous(expand = c(0, 0),
                       limits = c(-13, latest_rel + 11.2),
                       breaks = seq(0, 120, by = 20)) + 
    scale_y_continuous(expand = c(.003, .003),
                       limits = c(0, 1.08),
                       breaks = seq(0, 1, by = .25),
                       labels = scales::percent_format())

f + 
  ## remove grid lines annpotation areas left + right
  geom_rect(xmin = -Inf, xmax = 0,
            ymin = -Inf, ymax = Inf,
            fill = "white",
            inherit.aes = F) +
  geom_rect(xmin = latest_rel + 2.5, xmax = Inf,
            ymin = -Inf, ymax = Inf,
            fill = "white",
            inherit.aes = F) +
  ## trajectory highlighted
  geom_line(size = 1.4, color = "grey20") +
  ## point worst day highlighted
  geom_point(data = dff %>% filter(rel == 1),
             size = 2,
             color = "#e15383") +
  ## point latest value
  geom_point(data = dff %>% filter(yday == latest_day),
             size = 4.5,
             shape = 21,
             color = "white",
             fill = "black",
             stroke = .6) + #278f84
  geom_point(data = dff %>% filter(yday == latest_day),
             aes(color = rel),
             size = 2) +
  ## version with label showing latest daily numbers
  geom_label(data = dff %>% filter(yday == latest_day & country != "China*"),
            aes(label = lab_sum),
            size = 5,
            family = "Overpass",
            color = "grey20",
            fontface = "bold",
            hjust = 0,
            nudge_x = 4,
            lineheight = .9) +
  geom_label(data = dff %>% filter(yday == latest_day & country == "China*"),
            aes(label = lab_sum),
            size = 5,
            family = "Overpass",
            color = "grey20",
            fontface = "bold",
            vjust = 0,
            nudge_y = .08) +
  ## version with sum labels in rightupper corner
  # geom_label(data = dff %>% filter(yday == latest_day),
  #            aes(x = latest_rel + 10, y = .87, label = lab),
  #            size = 4.5,
  #            family = "Overpass",
  #            color = "grey20",
  #            fontface = "bold",
  #            hjust = 1) +
  ## label date first confirmed death
  geom_text(data = dff %>% filter(day_rel == 0),
            aes(label = glue::glue("{month} {day}")),
            size = 4,
            family = "Overpass",
            color = "grey20",
            fontface = "bold",
            hjust = 1,
            vjust = .5,
            nudge_x = -1) +
  ## label worst day so far
  geom_text(data = dff %>% filter(rel == 1) %>% 
              mutate(lab = format(round(max), big.mark = ",")) %>% 
              group_by(country) %>% filter(yday == min(yday)),
            aes(label = lab),
            size = 4.5,
            family = "Overpass",
            fontface = "bold",
            color = "#e15383",
            hjust = 1,
            nudge_x = -1.75,
            nudge_y = .07) +
  ## explanation note worst day so far
  geom_segment(data = dff %>% filter(rel == 1),
               aes(xend = xend, yend = yend),
               color = "#e15383",
               size = .6) +
  geom_label(data = dff %>% filter(rel == 1),
             aes(xend, .95, label = lab_worst),
             size = 5,
             family = "Overpass",
             fontface = "bold",
             color = "#e15383",
             lineheight = .9) +
  rcartocolor::scale_color_carto_c(palette = "PinkYl", guide = F) +
  labs(x = "Number of days since first confirmed death due to COVID-19",
       y = "COVID-19 death cases relative to each country's highest average daily death toll so far", 
       title = "<b style='color:#c93a6e;'>The Worst Days:</b> Peaks in Confirmed Daily Deaths Due to COVID-19 So Far",
       subtitle = subtitle_lab,
       caption = caption_lab) +
  theme(axis.text.y = element_text(colour = label_col, face = "bold"),
        axis.title.x = element_text(hjust = .15),
        plot.caption = element_markdown(margin = margin(t = 45, r = 50)))
        #axis.title.x = element_text(hjust = 0),
        #plot.caption = element_markdown(margin = margin(t = -120, r = 50)),
        #plot.margin = margin(20, 30, -10, 30)) 

ggsave(here::here("plots", "corona_trajectory_facet.pdf"),
       width = fig_width, height = fig_height, device = cairo_pdf)

setwd(here::here("plots"))
pdf_convert(pdf = here::here("plots", "corona_trajectory_facet.pdf"), 
              format = "png", dpi = 250)
```


```{r facets-plot-500+, fig.width = fig_width, fig.height = fig_height}
## only countries with more than 500 or more confirmed deaths
dff <- 
  df_corona_roll %>% 
  filter(
    sum >= 500, 
    country != "Worldwide"
  ) %>% 
  mutate(country = factor(country)) %>% 
  mutate(lab_sum = if_else(as.numeric(country) == 1, 
                           glue::glue("Total: {lab_sum}"),
                           lab_sum)) %>% 
  group_by(country) %>% 
  mutate(
    lab_worst = if_else(country == "Algeria", 
                        "Maximum daily\naverage so far", 
                        NA_character_),
    xend = if_else(country == "Algeria", day_rel + 37, NA_real_),
    yend = if_else(country == "Algeria", .825, NA_real_)
  )

f <- 
  ggplot(dff, 
         aes(day_rel, rel, 
             group = country)) +
    ## all trajectories
    geom_line(alpha = .2,
              size = .7) +
    ## all worst days as dots
    geom_point(data = dff %>% filter(yday == latest_day),
               alpha = 1,
               size = 1) +
    gghighlight(use_direct_label = F,
                unhighlighted_params = list(color = "grey70")) +
    facet_wrap(~ country, ncol = 7, scales = "free_x") +
    coord_cartesian(clip = "off") +
    scale_x_continuous(expand = c(0, 0),
                       limits = c(-13, latest_rel + 11.2),
                       breaks = seq(0, 120, by = 20)) + 
    scale_y_continuous(expand = c(.003, .003),
                       limits = c(0, 1.08),
                       breaks = seq(0, 1, by = .25),
                       labels = scales::percent_format())

f + 
  ## remove grid lines annpotation areas left + right
  geom_rect(xmin = -Inf, xmax = 0,
            ymin = -Inf, ymax = Inf,
            fill = "white",
            inherit.aes = F) +
  geom_rect(xmin = latest_rel + 2.5, xmax = Inf,
            ymin = -Inf, ymax = Inf,
            fill = "white",
            inherit.aes = F) +
  ## trajectory highlighted
  geom_line(size = 1.4, color = "grey20") +
  ## point worst day highlighted
  geom_point(data = dff %>% filter(rel == 1),
             size = 2,
             color = "#e15383") +
  ## point latest value
  geom_point(data = dff %>% filter(yday == latest_day),
             size = 4.5,
             shape = 21,
             color = "white",
             fill = "black",
             stroke = .6) + #278f84
  geom_point(data = dff %>% filter(yday == latest_day),
             aes(color = rel),
             size = 2) +
  ## version with label showing latest daily numbers
  geom_label(data = dff %>% filter(yday == latest_day & country != "China*"),
            aes(label = lab_sum),
            size = 5,
            family = "Overpass",
            color = "grey20",
            fontface = "bold",
            hjust = 0,
            nudge_x = 4,
            lineheight = .9) +
  geom_label(data = dff %>% filter(yday == latest_day & country == "China*"),
            aes(label = lab_sum),
            size = 5,
            family = "Overpass",
            color = "grey20",
            fontface = "bold",
            vjust = 0,
            nudge_y = .08) +
  ## label date first confirmed death
  geom_text(data = dff %>% filter(day_rel == 0),
            aes(label = glue::glue("{month} {day}")),
            size = 4,
            family = "Overpass",
            color = "grey20",
            fontface = "bold",
            hjust = 1,
            vjust = .5,
            nudge_x = -1) +
  ## label worst day so far
  geom_text(data = dff %>% filter(rel == 1) %>% 
              mutate(lab = format(round(max), big.mark = ",")) %>% 
              group_by(country) %>% filter(yday == min(yday)),
            aes(label = lab),
            size = 4.5,
            family = "Overpass",
            fontface = "bold",
            color = "#e15383",
            hjust = 1,
            nudge_x = -1.75,
            nudge_y = .07) +
  ## explanation note worst day so far
  geom_segment(data = dff %>% filter(rel == 1),
               aes(xend = xend, yend = yend),
               color = "#e15383",
               size = .6) +
  geom_label(data = dff %>% filter(rel == 1),
             aes(xend, .95, label = lab_worst),
             size = 5,
             family = "Overpass",
             fontface = "bold",
             color = "#e15383",
             lineheight = .9) +
  rcartocolor::scale_color_carto_c(palette = "PinkYl", guide = F) +
  labs(x = "Number of days since first confirmed death due to COVID-19",
       y = "COVID-19 death cases relative to each country's highest average daily death toll so far", 
       title = "<b style='color:#c93a6e;'>The Worst Days:</b> Peaks in Confirmed Daily Deaths Due to COVID-19 So Far",
       subtitle = "<b>Each panel shows the trajectory of confirmed deaths due to COVID-19 as percentage of daily deaths relative to the <i style='color:#c93a6e;'>worst day so far</i> for countries with at least 500 reported deaths.</b><span style='font-size:18pt;'><br><br>For each day, starting with the date of first reported death, the 7-day rolling average of confimed deaths per day is divided by the <b style='color:#c93a6e;'>highest average number of daily deaths so far defined as 100%</b>.<br>The text labels show the day of the first cofirmed death due to COVID-19 and the overall death toll per country.</span>",
       caption = "Note: Charts contain all confirmed deaths due to COVID-19 from January 22<sup>nd</sup> to May 28<sup>th</sup> 2020 for countries with 500 or more deaths.<br>* The deaths reported on April 17<sup>th</sup> in Wuhan, China, have been added proportionally to the confirmed daily deaths until that date.<br><br>**Visualization: Cédric Scherer  •  Data: Johns Hopkins University Center for Systems Science and Engineering (CSSE) via datahub.io**") +
  theme(axis.text.x = element_text(size = 12),
        axis.text.y = element_text(colour = label_col, face = "bold"),
        axis.title.x = element_text(hjust = .5),
        plot.caption = element_markdown(margin = margin(t = 45, r = 50)))
        #axis.title.x = element_text(hjust = 0),
        #plot.caption = element_markdown(margin = margin(t = -120, r = 50)),
        #plot.margin = margin(20, 30, -10, 30)) 

ggsave(here::here("plots", "corona_trajectory_facet_500.pdf"),
       width = fig_width, height = fig_height - 6.5, device = cairo_pdf)

setwd(here::here("plots"))
pdf_convert(pdf = here::here("plots", "corona_trajectory_facet_500.pdf"), 
              format = "png", dpi = 250)
```


## Plot: Global Trajectory

```{r overview-plot}
df <- 
  df_corona_roll %>% 
  filter(sum >= 100) %>% 
  mutate(
    country_lump = if_else(country %in% c("Worldwide", "China*", "Italy", "Spain", "France", 
                                         "Germany", "United Kingdom", "United States"), 
                          country, "Other"),
    country_lump = fct_reorder(country_lump, -day_first)
  )

ggplot(df, 
       aes(yday, rel, 
           group = country,
           color = country_lump)) +
  ## other countries
  geom_line(data = df %>% filter(country_lump == "Other"),
            color = "grey75",
            alpha = .2) +
  ## worst average days other countries
  geom_point(data = df %>% filter(country_lump != "Worldwide" & rel == 1), 
             color = "grey90") +
  ## highlighted countries (lines)
  geom_line(data = df %>% filter(country_lump != "Other")) +
  ## worst average days highlighted countries
  geom_point(data = df %>% filter(!country_lump %in% c("Worldwide", "Other") & rel == 1)) +
  ## highlighted countries (points)
  geom_point(data = df %>% filter(country_lump != "Other" & yday == latest_day), 
             size = 1.8,
             color = "black",
             stroke = .6) +
  geom_point(data = df %>% filter(country_lump != "Other" & yday == latest_day),
             size = 1.2) +
  ## worldwide
  geom_line(data = df %>% filter(country_lump == "Worldwide"),
            color = "black",
            size = 1) +
  geom_point(data = df %>% filter(country_lump == "Worldwide" & yday == latest_day),
             size = 4.5,
             shape = 21,
             color = "white",
             fill = "black",
             stroke = .6) + #278f84
  geom_point(data = df %>% filter(country_lump == "Worldwide" & yday == latest_day),
             aes(fill = rel),
             shape = 21,
             stroke = 0,
             size = 3) +
  coord_cartesian(clip = "off") +
  scale_x_continuous(expand = c(0, 0),
                     limits = c(first_day - 5, latest_day + 5)) +
  rcartocolor::scale_fill_carto_c(palette = "PinkYl", guide = F)

ggsave(here::here("plots", "corona_trajectory_overview.pdf"),
       width = 9.2, height = 6.7, device = cairo_pdf)
```


## Animation: Trajectories per Country

```{r facets-animation, fig.width = fig_width, fig.height = fig_height}
dfa <- 
  df_corona_roll %>% 
  filter(
    sum >= 100, 
    country != "Worldwide"
  ) %>% 
  group_by(country) %>% 
  mutate(start = min(yday[which(roll > 0)])) %>% 
  ungroup() %>% 
  mutate(country = fct_reorder(country, start))

for(i in first_day:latest_day) {
  print(i)
  
  ## only countries with more than 100 or more confirmed deaths
  df <-
    dfa %>% 
    filter(yday <= i) %>% 
    group_by(country) %>% 
    mutate(
      lab_sum = format(sum(daily, na.rm = T), big.mark = ","),
      lab_sum_a = if_else(as.numeric(country) == 1, 
                          glue::glue("Total: {lab_sum}"),
                          lab_sum),
      lab_sum_b = if_else(as.numeric(country) == 1, 
                          glue::glue("Total:\n{lab_sum}"),
                          lab_sum)
    )
  
  f <- 
    ggplot(df, 
           aes(day_rel, rel, 
               group = country)) +
      ## all trajectories
      geom_line(alpha = .2,
                size = .7) +
      ## all worst days as dots
      geom_point(data = df %>% filter(yday == latest_day),
                 alpha = 1,
                 size = 1) +
      gghighlight(use_direct_label = F,
                  unhighlighted_params = list(color = "grey80")) +
      facet_wrap(~ country, ncol = 8, drop = F) +
      coord_cartesian(clip = "off") +
      scale_x_continuous(expand = c(0, 0),
                         limits = c(-13, latest_rel + 11),
                         breaks = seq(0, 120, by = 20)) + 
      scale_y_continuous(expand = c(.003, .003),
                         limits = c(0, 1.08),
                         labels = scales::percent_format())
  
  f <- 
    f +
      ## trajectory highlighted
      geom_line(size = 1.4, color = "grey20") +
      ## point worst day highlighted
      geom_point(data = df %>% filter(rel == 1),
                 size = 2,
                 color = "#e15383") +
      ## add white space annotation areas left + right
      geom_rect(xmin = -Inf, xmax = 0,
                ymin = -Inf, ymax = Inf,
                fill = "white",
                inherit.aes = F) +
      geom_rect(xmin = latest_rel + 2.5, xmax = Inf,
                ymin = -Inf, ymax = Inf,
                fill = "white",
                inherit.aes = F) +
      ## point latest values
      geom_point(data = df %>% filter(yday == i),
                 size = 4.5,
                 shape = 21,
                 color = "white",
                 fill = "black",
                 stroke = .6) + #278f84
      geom_point(data = df %>% filter(yday == i),
                 aes(color = rel),
                 size = 2) +
      ## label total number of confirmed deaths
      geom_label(data = df %>% filter(yday == i & country != "China*"),
                 aes(label = lab_sum_a),
                 size = 5,
                 family = "Overpass",
                 color = "grey20",
                 fontface = "bold",
                 hjust = 0,
                 nudge_x = 4,
                 lineheight = .9) +
      ## label date first confirmed death
      geom_text(data = df %>% filter(day_rel == 0),
                aes(label = glue::glue("{month} {day}")),
                size = 4,
                family = "Overpass",
                color = "grey20",
                fontface = "bold",
                hjust = 1,
                vjust = .5,
                nudge_x = -2.35) +
      ## label worst day so far
      geom_text(data = df %>% filter(rel == 1) %>% 
                  mutate(lab = format(round(max), big.mark = ",")) %>% 
                  group_by(country) %>% filter(yday == min(yday)),
                aes(label = lab),
                size = 4.5,
                family = "Overpass",
                fontface = "bold",
                color = "#e15383",
                hjust = 1,
                nudge_x = -1.75,
                nudge_y = .07) +
      rcartocolor::scale_color_carto_c(palette = "PinkYl", guide = F) +
      labs(x = "Number of days since first confirmed death due to COVID-19",
           y = "COVID-19 death cases relative to each country's highest average daily death toll so far", 
           title = "<b style='color:#c93a6e;'>The Worst Days:</b> Peaks in Confirmed Daily Deaths Due to COVID-19 So Far",
           subtitle = subtitle_lab,
           caption = caption_lab) +
      theme(axis.title.x = element_text(hjust = 0),
            axis.text.y = element_text(colour = label_col, face = "bold"))
  
  if(i < latest_day - 32) {
    
    f +
      geom_label(data = df %>% filter(yday == i & country == "China*"),
                 aes(label = lab_sum_a),
                 size = 5,
                 family = "Overpass",
                 color = "grey20",
                 fontface = "bold",
                 hjust = 0,
                 nudge_x = 4,
                 lineheight = .9) 
  } else {

    f +
      geom_label(data = df %>% filter(yday == i & country == "China*"),
                 aes(label = lab_sum_b),
                 size = 5,
                 family = "Overpass",
                 color = "grey20",
                 fontface = "bold",
                 lineheight = .8,
                 vjust = 0,
                 nudge_y = .08)
  }
  
  ggsave(glue::glue(here::here("plots", "series_line", "corona_trajectory_{sprintf('%03d', i)}.pdf")),
         width = fig_width, height = fig_height, device = cairo_pdf)
}


if(i == latest_day) {
  ggsave(glue::glue(here::here("plots", "series_line", "corona_trajectory_latest.pdf")),
         width = fig_width, height = fig_height, device = cairo_pdf)
}

## convert pdf's to png's
setwd(here::here("plots", "series_line"))
pdfs <- list.files(here::here("plots", "series_line"), pattern = "*.pdf")

for(pdf in pdfs) {
  pdf_convert(pdf = here::here("plots", "series_line", pdf), 
              format = "png", dpi = 250)
}

## convert png's to gif
system("magick.exe -delay 20 *.png -delay 100 *latest_1.png -loop 0 corona_trajectory.gif")

pdf_convert(pdf = here::here("plots", "series_line", "corona_trajectory_latest.pdf"), 
            format = "png", dpi = 350)
```

***

```{r session-info}
sessionInfo()
```
