---
title: "Corona Worst-Day Heatmap"
author: "Cedric Scherer"
date: date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, fig.showtext = TRUE)
Sys.setlocale("LC_TIME", "C")
```


## Setup
  
```{r prep}
library(tidyverse)
library(lubridate)
library(colorspace)
library(ggtext)
library(pdftools)
library(magick)
library(showtext)

font_add_google("Open Sans", "Open Sans")
font_add_google("Overpass", "Overpass")
font_add_google("Overpass Mono", "Overpass Mono")

showtext_auto()

theme_set(theme_minimal(base_size = 16, base_family = "Open Sans"))
theme_update(axis.text.x = element_text(size = 14),
             axis.text.x.top = element_text(margin = margin(b = 5)),
             axis.text.y = element_text(size = 12, face = "bold", color = "black"),
             axis.ticks.x = element_line(color = "grey40", size = .4),
             axis.ticks.y = element_blank(),
             axis.ticks.length = unit(.3, "lines"),
             axis.title.y = element_text(face = "bold"),
             legend.position = "top",
             legend.title = element_text(size = 20, color = "grey40"),
             legend.text = element_text(family = "Overpass", size = 17, color = "grey40"),
             legend.margin = margin(5, 0, 20, 0),
             panel.grid = element_blank(),
             plot.title = element_markdown(family = "Overpass", size = 50, face = "bold",
                                           color = "grey20", hjust = .5, lineheight = 1.05,
                                           margin = margin(12, 0, 25, 0)),
             plot.title.position = "plot",
             plot.caption = element_markdown(size = 14, color = "grey20", lineheight = 1.1,
                                             hjust = 1, margin = margin(35, 0, 0, 0)),
             plot.margin = margin(20, 50, 20, 30))
```


## Data Preparation

```{r data}
## download atest data
df_corona <- readr::read_csv("https://datahub.io/core/covid-19/r/time-series-19-covid-combined.csv")

## deaths per day with clean column names, dates and country names 
df_corona_days <-
  df_corona %>% 
  dplyr::select(
    date = Date,
    country = `Country/Region`,
    state = `Province/State`,
    deaths = Deaths,
    lat = Lat,
    lng = Long
  ) %>% 
  group_by(country, date) %>% 
  summarize(
    deaths = sum(deaths, na.rm = T),
    lat = first(lat),
    lng = first(lng)
  ) %>% 
  group_by(country) %>%
  mutate(
    yday = yday(date),
    day = day(date),
    month = month(date, label = T)
  ) %>% 
  arrange(country, yday) %>% 
  mutate(
    daily = deaths - lag(deaths),
    daily = if_else(is.na(daily), deaths, daily),
    daily = if_else(daily < 0, 0, daily)
  ) %>% 
  ungroup() %>% 
  filter(yday >= min(yday[which(daily > 0)])) %>% 
  mutate(daily = if_else(daily <= 0, NA_real_, daily)) %>% 
  group_by(country) %>% 
  mutate(n = sum(daily > 0, na.rm = T)) %>% 
  ungroup() %>% 
  mutate(
    country = case_when(
      country == "US" ~ "United States",
      country == "Korea, South" ~ "South Korea",
      country == "Bosnia and Herzegovina" ~ "Bosnia–Herzegovina",
      country == "China" ~ "China*",
      country == "Spain" ~ "Spain^",
      country == "Congo (Kinshasa)" ~ "DR Congo",
      country == "Congo (Brazzaville)" ~ "Congo-Brazzaville",
      TRUE ~ country
    ),
    country = str_replace(country, " and ", " & ")
  )

## summary of confirmed deaths worldwide
df_corona_world <-
  df_corona_days %>% 
  group_by(date, yday, day, month) %>% 
  summarize_at(
    vars(c("deaths", "daily")), sum, na.rm = T
  ) %>% 
  ungroup() %>% 
  filter(daily > 0) %>% 
  mutate(
    country = "Worldwide",
    n  = sum(daily > 0, na.rm = T),
    lat = 0,
    lng = 0
  )

## fix deaths in Wuhan, China, that were reported late
china_deaths <- 
  df_corona_days %>% 
  filter(country == "China*" & yday == 108) %>% ## April 17th
  pull(daily)

df_corona_china_fix <-
  df_corona_days %>% 
  filter(country == "China*" & yday <= 108) %>% 
  mutate(
    daily = if_else(yday == 108, 0, daily),
    daily = if_else(is.na(daily), 0, daily),
    daily = daily + round(daily * china_deaths / sum(daily)),
    daily = if_else(daily == max(daily), daily - 3, daily),
    daily = if_else(daily == 0, NA_real_, daily)
  ) 

## fix deaths in Spain, that were revised later
spain_deaths <- 
  df_corona_days %>% 
  filter(country == "Spain^" & yday == 171) %>% ## June 19th
  pull(daily)

df_corona_spain_fix <-
  df_corona_days %>% 
  filter(country == "Spain^" & yday <= 171) %>% 
  mutate(
    daily = if_else(yday == 171, 0, daily),
    daily = if_else(is.na(daily), 0, daily),
    daily = daily + round(daily * spain_deaths / sum(daily)),
    daily = if_else(daily == max(daily), daily + 5, daily),
    daily = if_else(daily == 0, NA_real_, daily)
  ) 

## only countries with 50 or more confirmed deaths + factorize countries
df_corona_fct <- 
  df_corona_days %>% 
  filter(
    !(country == "China*" & yday <= 108) &
    !(country == "Spain^" & yday <= 171)
  ) %>% 
  bind_rows(df_corona_world) %>% 
  bind_rows(df_corona_china_fix) %>% 
  bind_rows(df_corona_spain_fix) %>% 
  group_by(country) %>% 
  mutate(sum = sum(daily, na.rm = T)) %>% 
  filter(sum >= 200) %>%
  mutate(day_first = min(yday[which(!is.na(daily))])) %>% 
  ungroup() %>% 
  mutate(country = factor(country))

first_day <- min(df_corona_fct$yday)
latest_day <- max(df_corona_fct$yday)
n_countries <- n_distinct(df_corona_fct$country)

df_dates <-
  df_corona_fct %>% 
  filter(date %in% c(min(date, na.rm = T),
                     ymd("2020-02-01"),
                     ymd("2020-02-15"),
                     ymd("2020-03-01"),
                     ymd("2020-03-15"),
                     ymd("2020-04-01"),
                     ymd("2020-04-15"),
                     ymd("2020-05-01"),
                     ymd("2020-05-15"),
                     ymd("2020-06-01"),
                     max(date, na.rm = T))) %>% 
  group_by(date, yday) %>% 
  summarize(label = unique(glue::glue("{month(date, label = T)} {day(date)}")))

dates <- df_dates$yday
(dates_lab <- df_dates$label)

fig_width <- 35.8
fig_height <- 19.8
```


## Animations

### ranked by total confirmed deaths

```{r animation-ranked-by-death-toll, fig.width = fig_width, fig.height = fig_height}
#for(i in first_day:latest_day) {
for(i in 44:latest_day) {
  print(i)
  
  df <-
    df_corona_fct %>% 
    filter(yday <= i) %>% 
    group_by(country) %>% 
    mutate(
      max = max(daily, na.rm = T),
      rel = daily / max,
      rel = if_else(rel < 0, 0, rel),
      sum = sum(daily, na.rm = T),
      day_max = max(yday[which(rel == 1)]),
      lab = format(sum, big.mark = ","),
      lab = format(sum, big.mark = ","),
      lab = if_else(country == "Worldwide", 
                    glue::glue("**{lab}**"), 
                    glue::glue("{lab}")),
      lab_daily = if_else(daily >= 1000, 
                          glue::glue("{floor(daily / 1000)}K+"), 
                          as.character(daily))
    ) %>% 
    ungroup() %>% 
    ## rank by day of overall number of confirmed deaths
    mutate(country = fct_reorder(country, sum))
  
  ## one dot per country for given dates
  df_dots <- 
    df_corona_fct %>% 
    filter(yday %in% dates) %>% 
    mutate(country = factor(country, levels = levels(df$country)))
  
  ## colored labels on the right hand side
  df_labs <-
    df %>% 
    filter(yday == i) %>% 
    mutate(imp = if_else(day_max > 0, 1, 0))
  
  g <-
    ggplot(df,
           aes(country,
               yday, 
               group = yday)) +
      geom_point(data = df_dots,
                 aes(country, yday),
                 color = "grey50",
                 shape = 20,
                 size = .1) +
      geom_tile(aes(color = rel,
                    fill = rel),
                size = .1) +
      geom_richtext(data = df %>% filter(yday == i),
                    aes(country,
                        21.4,
                        label = lab),
                    family = "Overpass Mono",
                    size = 3.8,
                    fill = NA, 
                    label.color = NA,
                    
                    hjust = 1,
                    vjust = .6) +
      geom_segment(aes(x = n_countries - .5,
                       xend = n_countries - .5,
                       y = 18,
                       yend = i + .5),
                   color = "grey40",
                   size = .2) +
      coord_flip(clip = "off") +
      scale_x_discrete(expand = c(.001, .001)) +
      scale_y_continuous(expand = c(.001, 0.01),
                         limits = c(17.3, latest_day + 7),
                         sec.axis = dup_axis(),
                         breaks = dates,
                         labels = dates_lab) + 
      rcartocolor::scale_color_carto_c(palette = "PinkYl", 
                                       na.value = "#badad0",
                                       limits = c(0, 1),
                                       guide = F) +
      rcartocolor::scale_fill_carto_c(palette = "PinkYl", 
                                      na.value = "#badad0",
                                      name = "COVID-19 death cases relative to each country's highest daily death toll so far",
                                      limits = c(0, 1),
                                      breaks = c(.001, seq(.25, 1, by = .25)),
                                      labels = c("0.1% of daily max", "25% of daily max", 
                                                 "50% of daily max", "75% of daily max", 
                                                 "Worst day so far")) +
                                      #breaks = c(.01, seq(.1, 1, by = .1)),
                                      #labels = scales::percent_format(accuracy = 1)) +
      guides(fill = guide_colorbar(title.position = "top",
                                   title.hjust = .5,
                                   label.position = "bottom",
                                   label.hjust = .5,
                                   barwidth = unit(55, "lines"),
                                   barheight = unit(.75, "lines"))) +
      labs(x = NULL, y = NULL, 
           title = "<b style='color:#c93a6e;'>The Worst Days:</b> Peaks in Confirmed Daily Deaths Due to COVID-19 So Far",
           caption = "The visualization shows **countries with at least 200 reported deaths** due to the corona virus disease 2019 (COVID-19). The color intensity for each day and country is estimated as<br>the number of deaths on this particular day divided by the highest daily death toll so far. The countries are ranked by the overall number of confirmed deaths due to COVID-19.<br><br><span style='font-size:11pt'>* On April 17<sup>th</sup> 2020, officials in Wuhan, China, revised the city´s coronavirus death toll. The deaths have been added proportionally to the daily confirmed deaths of China until that date.<br>^ On June 19<sup>th</sup> the Spanish Ministry of Health has issued a revised death total for Spain. The deaths have been added proportionally to the daily confirmed deaths of Spain until that date.</span><br><br>**Visualization: Cédric Scherer  •  Data: Johns Hopkins University Center for Systems Science and Engineering (CSSE) via datahub.io**")
  
  g_daily <-
    g +
      geom_text(data = df %>% filter(yday == i),
                aes(country,
                    yday,
                    label = lab_daily),
                family = "Overpass",
                color = "black",
                fontface = "bold",
                size = 2.2,
                hjust = .5) +
      geom_label(data = df_labs,
                 aes(country,
                     i + .8,
                     label = country),
                 family = "Open Sans",
                 color = "white",
                 fontface = "bold",
                 size = 3.7,
                 hjust = 0,
                 label.size = NA,
                 label.padding = unit(0.2, "lines")) +
      geom_text(data = df_labs,
                 aes(country,
                     i + .8,
                     label = country,
                     alpha = imp),
                 family = "Open Sans",
                 color = "black",
                 fontface = "bold",
                 size = 3.7,
                 hjust = 0) +
      scale_alpha(range = c(.3, 1),
                  limits = c(0, 1),
                  guide = F)
  
  ggsave(here::here("plots", "series_heat_sum", 
                    glue::glue("corona_heat_sum_{sprintf('%03d', i)}.pdf")),
         width = fig_width, height = fig_height, device = cairo_pdf)
  
  if(i == latest_day) {
    g_latest <- 
      g +
        geom_tile(data = df %>% filter(rel == 1),
                  color = "black",
                  fill = NA,
                  size = .5) +
        geom_text(data = df %>% filter(yday == i),
                  aes(country,
                      yday,
                      label = lab_daily),
                  family = "Overpass",
                  color = "grey40",
                  size = 2.2,
                  hjust = .5) +
        geom_text(data = df %>% filter(rel == 1),
                  aes(country,
                      yday,
                      label = lab_daily),
                  family = "Overpass",
                  fontface = "bold",
                  size = 2.2,
                  hjust = .5) +
        geom_text(data = df_labs,
                  aes(country,
                      latest_day + .8,
                      label = country,
                      color = rel,
                      color = after_scale(darken(color, .15, space = "HLS"))),
                  family = "Open Sans",
                  fontface = "bold",
                  size = 3.7,
                  hjust = 0)
    
    ggsave(here::here("plots", "series_heat_sum", glue::glue("corona_heat_sum_latest.pdf")),
           width = fig_width, height = fig_height, device = cairo_pdf)
  }
}

## convert pdf's to png's
setwd(here::here("plots", "series_heat_sum"))
pdfs <- list.files(here::here("plots", "series_heat_sum"), pattern = "*.pdf")

for(pdf in pdfs) {
  pdf_convert(pdf = here::here("plots", "series_heat_sum", pdf), 
              format = "png", dpi = 120)
}

## convert png's to gif
system("magick.exe -delay 30 *.png -delay 120 *latest_1.png -loop 0 corona_heat_sum.gif")

pdf_convert(pdf = here::here("plots", "series_heat_sum", "corona_heat_sum_latest.pdf"), 
              format = "png", dpi = 700)
```


### ranked by day of first confirmed death case

```{r animation-ranked-by-begin, fig.width = fig_width, fig.height = fig_height}
for(i in first_day:latest_day) {
#for(i in 44:latest_day) {  
  print(i)
  
  df <-
    df_corona_fct %>% 
    filter(yday <= i) %>% 
    group_by(country) %>% 
    mutate(
      max = max(daily, na.rm = T),
      rel = daily / max,
      rel = if_else(rel < 0, 0, rel),
      sum = sum(daily, na.rm = T),
      day_max = max(yday[which(rel == 1)]),
      lab = format(sum, big.mark = ","),
      lab = if_else(country == "Worldwide", 
                    glue::glue("**{lab}**"), 
                    glue::glue("{lab}")),
      lab_daily = if_else(daily >= 1000, 
                          glue::glue("{floor(daily / 1000)}K+"), 
                          as.character(daily))
    ) %>% 
    ungroup() %>% 
    ## rank by day of first confirmed deaths
    mutate(country = fct_reorder(country, -day_first))
  
  ## one dot per country for given dates
  df_dots <- 
    df_corona_fct %>% 
    filter(yday %in% dates) %>% 
    mutate(country = factor(country, levels = levels(df$country)))
  
  ## colored labels on the right hand side
  df_labs <-
    df %>% 
    filter(yday == i) %>% 
    mutate(imp = if_else(day_max > 0, 1, 0))
  
  g <-
    ggplot(df,
           aes(country,
               yday, 
               group = yday)) +
      geom_point(data = df_dots,
                aes(country, yday),
                color = "grey50",
                shape = 20,
                size = .01) +
      geom_tile(aes(color = rel,
                    fill = rel),
                size = .1) +
      geom_richtext(data = df %>% filter(yday == i),
                    aes(country,
                        21.4,
                        label = lab),
                    family = "Overpass Mono",
                    size = 3.8,
                    fill = NA, 
                    label.color = NA,
                    hjust = 1,
                    vjust = .6) +
      geom_segment(aes(x = n_countries - .5,
                       xend = n_countries - .5,
                       y = 18,
                       yend = i + .5),
                   color = "grey40",
                   size = .2) +
      coord_flip(clip = "off") +
      scale_x_discrete(expand = c(.001, 0.01)) +
      scale_y_continuous(expand = c(.001, 0.01),
                         limits = c(17.3, latest_day + 7),
                         sec.axis = dup_axis(),
                         breaks = dates,
                         labels = dates_lab) + 
      rcartocolor::scale_color_carto_c(palette = "PinkYl", 
                                       na.value = "#badad0",
                                       limits = c(0, 1),
                                       guide = F) +
      rcartocolor::scale_fill_carto_c(palette = "PinkYl", 
                                      na.value = "#badad0",
                                      name = "COVID-19 death cases relative to each country's highest daily death toll so far",
                                      limits = c(0, 1),
                                      breaks = c(.001, seq(.25, 1, by = .25)),
                                      labels = c("0.1% of daily max", "25% of daily max", 
                                                 "50% of daily max", "75% of daily max", 
                                                 "Worst day so far")) +
                                      #breaks = c(.01, seq(.1, 1, by = .1)),
                                      #labels = scales::percent_format(accuracy = 1)) +
      guides(fill = guide_colorbar(title.position = "top",
                                   title.hjust = .5,
                                   #label.position = "bottom",
                                   label.hjust = .5,
                                   barwidth = unit(55, "lines"),
                                   barheight = unit(.75, "lines"))) +
    labs(x = NULL, y = NULL, 
         title = "<b style='color:#c93a6e;'>The Worst Days:</b> Peaks in Confirmed Daily Deaths Due to COVID-19 So Far",
         caption = "**The visualization shows countries with at least 200 reported deaths due to the corona virus disease (COVID-19).** The color intensity for each day and country is estimated as<br>the number of deaths on this particular day divided by the highest daily death toll so far. The countries are ranked by the day of the first confirmed death due to COVID-19.<br><br><span style='font-size:11pt'>* On April 17<sup>th</sup> 2020, officials in Wuhan, China, revised the city´s coronavirus death toll. The deaths have been added proportionally to the daily confirmed deaths of China until that date.<br>^ On June 19<sup>th</sup> the Spanish Ministry of Health has issued a revised death total for Spain. The deaths have been added proportionally to the daily confirmed deaths of Spain until that date.</span><br><br>**Visualization: Cédric Scherer  •  Data: Johns Hopkins University Center for Systems Science and Engineering (CSSE) via datahub.io**")
  
  g_daily <- 
    g +
      geom_text(data = df %>% filter(yday == i),
                aes(country,
                    yday,
                    label = lab_daily),
                family = "Overpass",
                color = "black",
                fontface = "bold",
                size = 2.2,
                hjust = .5) +
      geom_label(data = df_labs,
                 aes(country,
                     i + .8,
                     label = country),
                 family = "Open Sans",
                 color = "white",
                 fontface = "bold",
                 size = 3.7,
                 hjust = 0,
                 label.size = NA,
                 label.padding = unit(0.2, "lines")) +
      geom_text(data = df_labs,
                 aes(country,
                     i + .8,
                     label = country,
                     alpha = imp),
                 family = "Open Sans",
                 color = "black",
                 fontface = "bold",
                 size = 3.7,
                 hjust = 0) +
      scale_alpha(range = c(.3, 1),
                  limits = c(0, 1),
                  guide = F)
  
  ggsave(here::here("plots", "series_heat_begin", 
                    glue::glue("corona_heat_begin_{sprintf('%03d', i)}.pdf")),
         width = fig_width, height = fig_height, device = cairo_pdf)
  
  if(i == latest_day) {
    g_latest <- 
      g +
        geom_tile(data = df %>% filter(rel == 1),
                  color = "black",
                  fill = NA,
                  size = .5) +
        geom_text(data = df %>% filter(yday == i),
                  aes(country,
                      yday,
                      label = lab_daily),
                  family = "Overpass",
                  color = "grey20",
                  size = 2.2,
                  hjust = .5) +
        geom_text(data = df %>% filter(rel == 1),
                  aes(country,
                      yday,
                      label = lab_daily),
                  family = "Overpass",
                  fontface = "bold",
                  size = 2.2,
                  hjust = .5) +
        geom_text(data = df_labs,
                  aes(country,
                      latest_day + .8,
                      label = country,
                      color = rel,
                      color = after_scale(darken(color, .15, space = "HLS"))),
                  family = "Open Sans",
                  fontface = "bold",
                  size = 3.7,
                  hjust = 0)
    
    ggsave(here::here("plots", "series_heat_begin", glue::glue("corona_heat_begin_latest.pdf")),
           width = fig_width, height = fig_height, device = cairo_pdf)
  }
}


## convert pdf's to png's
setwd(here::here("plots", "series_heat_begin"))
pdfs <- list.files(here::here("plots", "series_heat_begin"), pattern = "*.pdf")

for(pdf in pdfs) {
  pdf_convert(pdf = here::here("plots", "series_heat_begin", pdf), 
              format = "png", dpi = 120)
}

## convert png's to gif
system("magick.exe -delay 30 *.png -delay 120 *latest_1.png -loop 0 corona_heat_begin.gif")

pdf_convert(pdf = here::here("plots", "series_heat_begin", "corona_heat_begin_latest.pdf"), 
              format = "png", dpi = 700)
```


### ranked by Longitude

```{r animation-ranked-by-longitude, fig.width = fig_width, fig.height = fig_height}
#for(i in first_day:latest_day) {
for(i in 44:latest_day) {  
  print(i)
  
  df <-
    df_corona_fct %>% 
    filter(yday <= i) %>% 
    group_by(country) %>% 
    mutate(
      max = max(daily, na.rm = T),
      rel = daily / max,
      rel = if_else(rel < 0, 0, rel),
      sum = sum(daily, na.rm = T),
      day_max = max(yday[which(rel == 1)]),
      lab = format(sum, big.mark = ","),
      lab = format(sum, big.mark = ","),
      lab = if_else(country == "Worldwide", 
                    glue::glue("**{lab}**"), 
                    glue::glue("{lab}")),
      lab_daily = if_else(daily >= 1000, 
                          glue::glue("{floor(daily / 1000)}K+"), 
                          as.character(daily))
    ) %>% 
    ungroup() %>% 
    ## rank by day of first confirmed deaths
    mutate(country = fct_reorder(country, lng)) %>% 
    mutate(country = fct_relevel(country, "Worldwide", after = Inf))
  
  ## one dot per country for given dates
  df_dots <- 
    df_corona_fct %>% 
    filter(yday %in% dates) %>% 
    mutate(country = factor(country, levels = levels(df$country)))
  
  ## colored labels on the right hand side
  df_labs <-
    df %>% 
    filter(yday == i) %>% 
    mutate(imp = if_else(day_max > 0, 1, 0))
  
  g <-
    ggplot(df,
           aes(country,
               yday, 
               group = yday)) +
      geom_point(data = df_dots,
                aes(country, yday),
                color = "grey50",
                shape = 20,
                size = .01) +
      geom_tile(aes(color = rel,
                    fill = rel),
                size = .1) +
      geom_richtext(data = df %>% filter(yday == i),
                    aes(country,
                        21.4,
                        label = lab),
                    family = "Overpass Mono",
                    size = 3.8,
                    fill = NA, 
                    label.color = NA,
                    hjust = 1,
                    vjust = .6) +
      geom_segment(aes(x = n_countries - .5,
                       xend = n_countries - .5,
                       y = 18,
                       yend = i + .5),
                   color = "grey20",
                   size = .4) +
      coord_flip(clip = "off") +
      scale_x_discrete(expand = c(.001, 0.01)) +
      scale_y_continuous(expand = c(.001, 0.01),
                         limits = c(17.3, latest_day + 7),
                         sec.axis = dup_axis(),
                         breaks = dates,
                         labels = dates_lab) + 
      rcartocolor::scale_color_carto_c(palette = "PinkYl", 
                                       na.value = "#badad0",
                                       limits = c(0, 1),
                                       guide = F) +
      rcartocolor::scale_fill_carto_c(palette = "PinkYl", 
                                      na.value = "#badad0",
                                      name = "COVID-19 death cases relative to each country's highest daily death toll so far",
                                      limits = c(0, 1),
                                      breaks = c(.001, seq(.25, 1, by = .25)),
                                      labels = c("0.1% of daily max", "25% of daily max", 
                                                 "50% of daily max", "75% of daily max", 
                                                 "Worst day so far")) +
                                      #breaks = c(.01, seq(.1, 1, by = .1)),
                                      #labels = scales::percent_format(accuracy = 1)) +
      guides(fill = guide_colorbar(title.position = "top",
                                   title.hjust = .5,
                                   label.position = "bottom",
                                   label.hjust = .5,
                                   barwidth = unit(55, "lines"),
                                   barheight = unit(.75, "lines"))) +
    labs(x = NULL, y = NULL, 
         title = "<b style='color:#c93a6e;'>The Worst Days:</b> Peaks in Confirmed Daily Deaths Due to COVID-19 So Far",
         caption = "**The visualization shows countries with at least 200 reported deaths due to the corona virus disease (COVID-19).** The color intensity for each day and country is estimated as<br>the number of deaths on this particular day divided by the highest daily death toll so far. The countries are ranked by the latitude of their centroid.<br><br><span style='font-size:11pt'>* On April 17<sup>th</sup> 2020, officials in Wuhan, China, revised the city´s coronavirus death toll. The deaths have been added proportionally to the daily confirmed deaths of China until that date.<br>^ On June 19<sup>th</sup> the Spanish Ministry of Health has issued a revised death total for Spain. The deaths have been added proportionally to the daily confirmed deaths of Spain until that date.</span><br><br>**Visualization: Cédric Scherer  •  Data: Johns Hopkins University Center for Systems Science and Engineering (CSSE) via datahub.io**")
  
  g_daily <- 
    g +
      geom_text(data = df %>% filter(yday == i),
                aes(country,
                    yday,
                    label = lab_daily),
                family = "Overpass",
                color = "black",
                fontface = "bold",
                size = 2.2,
                hjust = .5) +
      geom_label(data = df_labs,
                 aes(country,
                     i + .8,
                     label = country),
                 family = "Open Sans",
                 color = "white",
                 fontface = "bold",
                 size = 3.7,
                 hjust = 0,
                 label.size = NA,
                 label.padding = unit(0.2, "lines")) +
      geom_text(data = df_labs,
                 aes(country,
                     i + .8,
                     label = country,
                     alpha = imp),
                 family = "Open Sans",
                 color = "black",
                 fontface = "bold",
                 size = 3.7,
                 hjust = 0) +
      scale_alpha(range = c(.3, 1),
                  limits = c(0, 1),
                  guide = F)
  
  ggsave(here::here("plots", "series_heat_lng", 
                    glue::glue("corona_heat_lng_{sprintf('%03d', i)}.pdf")),
         width = fig_width, height = fig_height, device = cairo_pdf)
  
  if(i == latest_day) {
    g_latest <- 
      g +
        geom_tile(data = df %>% filter(rel == 1),
                  color = "black",
                  fill = NA,
                  size = .5) +
        geom_text(data = df %>% filter(yday == i),
                  aes(country,
                      yday,
                      label = lab_daily),
                  family = "Overpass",
                  color = "grey20",
                  size = 2.2,
                  hjust = .5) +
        geom_text(data = df %>% filter(rel == 1),
                  aes(country,
                      yday,
                      label = lab_daily),
                  family = "Overpass",
                  fontface = "bold",
                  size = 2.2,
                  hjust = .5) +
        geom_text(data = df_labs,
                  aes(country,
                      latest_day + .8,
                      label = country,
                      color = rel,
                      color = after_scale(darken(color, .15, space = "HLS"))),
                  family = "Open Sans",
                  fontface = "bold",
                  size = 3.7,
                  hjust = 0)
    
    ggsave(here::here("plots", "series_heat_lng", glue::glue("corona_heat_lng_latest.pdf")),
           width = fig_width, height = fig_height, device = cairo_pdf)
  }
}

sw
## convert pdf's to png's
setwd(here::here("plots", "series_heat_lng"))
pdfs <- list.files(here::here("plots", "series_heat_lng"), pattern = "*.pdf")

for(pdf in pdfs) {
  pdf_convert(pdf = here::here("plots", "series_heat_lng", pdf), 
              format = "png", dpi = 200)
}

## convert png's to gif
system("magick.exe -delay 30 *.png -delay 120 *latest_1.png -loop 0 corona_heat_lng.gif")

pdf_convert(pdf = here::here("plots", "series_heat_lng", "corona_heat_lng_latest.pdf"), 
              format = "png", dpi = 700)
```


## Static Plot

### ranked by latest trend (worst day + total deaths)

```{r static-plot-trend, fig.width = fig_width, fig.height = fig_height + .5}
df <- 
  df_corona_fct %>% 
  group_by(country) %>% 
  arrange(country, yday) %>% 
  mutate(
      max = max(daily, na.rm = T),
      rel = daily / max,
      rel = if_else(rel < 0, 0, rel),
      worse = if_else(lag(rel) <= rel, T, F),
      worse = if_else(is.na(worse), T, worse),
      lab = format(sum, big.mark = ","),
      lab = if_else(country == "Worldwide", 
                    glue::glue("**{lab}**"), 
                    glue::glue("{lab}")),
      lab_daily = if_else(daily >= 1000, 
                          glue::glue("{floor(daily / 1000)}K+"), 
                          as.character(daily)),
      day_max = max(yday[which(rel == 1)]),
      ## rank first by latest "worst day", then by total deaths
      trend = day_max + daily[which(yday == latest_day)] / 100000,
      trend = if_else(is.na(trend), day_max, trend)
    ) %>% 
    ungroup() %>% 
    ## rank by trend and put worldwide on top
    mutate(country = fct_reorder(country, trend)) %>% 
    mutate(country = fct_relevel(country, "Worldwide", after = Inf))
  
## colored labels on the right hand side
df_labs <- filter(df, yday == latest_day)

ggplot(df,
       aes(country,
           yday, 
           group = yday)) +
  geom_tile(aes(color = rel,
                fill = rel),
            size = .1) +
  geom_richtext(data = df %>% filter(yday == latest_day),
                aes(country,
                    21.4,
                    label = lab),
                family = "Overpass Mono",
                size = 3.8,
                fill = NA, 
                label.color = NA,
                hjust = 1,
                vjust = .6) +
  geom_segment(aes(x = n_countries - .5,
                   xend = n_countries - .5,
                   y = 17.3,
                   yend = latest_day + .5),
               color = "grey40",
             size = .2) +
  geom_tile(data = df %>% filter(rel == 1),
            color = "black",
            fill = NA,
            size = .5) +
  geom_text(data = df %>% filter(yday == latest_day),
            aes(country,
                yday,
                label = lab_daily),
            family = "Overpass",
            color = "grey20",
            size = 2.2,
            hjust = .5) +
  geom_text(data = df %>% filter(rel == 1),
            aes(country,
                yday,
                label = lab_daily),
            family = "Overpass",
            fontface = "bold",
            size = 2.2,
            hjust = .5) +
  geom_text(data = df_labs,
            aes(country,
                latest_day + .8,
                label = country,
                color = rel,
                color = after_scale(darken(color, .15, space = "HLS"))),
            family = "Open Sans",
            fontface = "bold",
            size = 3.7,
            hjust = 0) +
  coord_flip(clip = "off") +
  scale_x_discrete(expand = c(.001, 0.01)) +
  scale_y_continuous(expand = c(.001, 0.01),
                     limits = c(17.3, latest_day + 7),
                     sec.axis = dup_axis(),
                     breaks = dates,
                     labels = dates_lab) + 
  rcartocolor::scale_color_carto_c(palette = "PinkYl", 
                                   na.value = "#badad0",
                                   limits = c(0, 1),
                                   guide = F) +
  rcartocolor::scale_fill_carto_c(palette = "PinkYl", 
                                  na.value = "#badad0",
                                  name = "COVID-19 death cases relative to each country's highest daily death toll so far",
                                  limits = c(0, 1),
                                  breaks = c(.001, seq(.25, 1, by = .25)),
                                  labels = c("0.1% of daily max", "25% of daily max", 
                                             "50% of daily max", "75% of daily max", 
                                             "Worst day so far")) +
                                  #breaks = c(.01, seq(.1, 1, by = .1)),
                                  #labels = scales::percent_format(accuracy = 1)) +
  guides(fill = guide_colorbar(title.position = "top",
                               title.hjust = .5,
                               label.position = "bottom",
                               label.hjust = .5,
                               barwidth = unit(55, "lines"),
                               barheight = unit(.75, "lines"))) +
  labs(x = NULL, y = NULL, 
       title = "<b style='color:#c93a6e;'>The Worst Days:</b> Which Countries are Currently Experiencing the Highest<br>Number of Confirmed Daily Deaths Due to COVID-19 So Far?",
       caption = '**The visualization shows countries with at least 200 reported deaths due to the corona virus disease (COVID-19).** The color intensity for each day and country is estimated as the<br>number of deaths on this particular day divided by the highest daily death toll so far. The countries are ranked by time since the latest "worst day" and number of reported daily deaths.<br><br><span style="font-size:11pt">* On April 17<sup>th</sup> 2020, officials in Wuhan, China, revised the city´s coronavirus death toll. The deaths have been added proportionally to the daily confirmed deaths of China until that date.<br>^ On June 19<sup>th</sup> the Spanish Ministry of Health has issued a revised death total for Spain. The deaths have been added proportionally to the daily confirmed deaths of Spain until that date.</span><br><br>**Visualization: Cédric Scherer  •  Data: Johns Hopkins University Center for Systems Science and Engineering (CSSE) via datahub.io**')

ggsave(here::here("plots", glue::glue("corona_heat_trend_latest.pdf")),
       width = fig_width, height = fig_height + .5, device = cairo_pdf)

## convert pdf to png
setwd(here::here("plots"))
pdf_convert(pdf = here::here("plots", "corona_heat_trend_latest.pdf"), 
            format = "png", dpi = 500)
```


### compact version starting Feb 23 (worst day in China)

```{r static-plot-trend-compact, fig.width = fig_width - 3, fig.height = fig_height + .5}
df %>% 
  filter(date >= ymd("2020-02-13")) %>% 
  ggplot(aes(country,
             yday, 
             group = yday)) +
    geom_tile(aes(color = rel,
                  fill = rel),
              size = .1) +
    geom_richtext(data = df %>% filter(yday == latest_day),
                  aes(country,
                      43.2,
                      label = lab),
                  family = "Overpass Mono",
                  size = 3.8,
                  fill = NA, 
                  label.color = NA,
                  hjust = 1,
                  vjust = .6) +
    geom_segment(aes(x = n_countries - .5,
                     xend = n_countries - .5,
                     y = 40.2,
                     yend = latest_day + .5),
                 color = "grey40",
               size = .2) +
    geom_tile(data = df %>% filter(rel == 1),
              color = "black",
              fill = NA,
              size = .5) +
    geom_text(data = df %>% filter(yday == latest_day),
              aes(country,
                  yday,
                  label = lab_daily),
              family = "Overpass",
              color = "grey20",
              size = 2.2,
              hjust = .5) +
    geom_text(data = df %>% filter(rel == 1),
              aes(country,
                  yday,
                  label = lab_daily),
              family = "Overpass",
              fontface = "bold",
              size = 2.2,
              hjust = .5) +
    geom_text(data = df_labs,
              aes(country,
                  latest_day + .8,
                  label = country,
                  color = rel,
                  color = after_scale(darken(color, .15, space = "HLS"))),
              family = "Open Sans",
              fontface = "bold",
              size = 3.7,
              hjust = 0) +
    coord_flip(clip = "off") +
    scale_x_discrete(expand = c(.001, 0.01)) +
    scale_y_continuous(expand = c(.001, 0.01),
                       limits = c(40.2, latest_day + 7),
                       sec.axis = dup_axis(),
                       breaks = dates,
                       labels = dates_lab) + 
    rcartocolor::scale_color_carto_c(palette = "PinkYl", 
                                     na.value = "#badad0",
                                     limits = c(0, 1),
                                     guide = F) +
    rcartocolor::scale_fill_carto_c(palette = "PinkYl", 
                                    na.value = "#badad0",
                                    name = "COVID-19 death cases relative to each country's highest daily death toll so far",
                                    limits = c(0, 1),
                                    breaks = c(.001, seq(.25, 1, by = .25)),
                                    labels = c("0.1% of daily max", "25% of daily max", 
                                               "50% of daily max", "75% of daily max", 
                                               "Worst day so far")) +
                                    #breaks = c(.01, seq(.1, 1, by = .1)),
                                    #labels = scales::percent_format(accuracy = 1)) +
    guides(fill = guide_colorbar(title.position = "top",
                                 title.hjust = .5,
                                 label.position = "bottom",
                                 label.hjust = .5,
                                 barwidth = unit(55, "lines"),
                                 barheight = unit(.75, "lines"))) +
    labs(x = NULL, y = NULL, 
         title = "<b style='color:#c93a6e;'>The Worst Days:</b> Which Countries are Currently Experiencing the Highest<br>Number of Confirmed Daily Deaths Due to COVID-19 So Far?",
         caption = '**The visualization shows countries with at least 200 reported deaths due to the corona virus disease (COVID-19).** The color intensity for each day and country is estimated as the<br>number of deaths on this particular day divided by the highest daily death toll so far. The countries are ranked by time since the latest "worst day" and number of reported daily deaths.<br><br><span style="font-size:11pt">* On April 17<sup>th</sup> 2020, officials in Wuhan, China, revised the city´s coronavirus death toll. The deaths have been added proportionally to the daily confirmed deaths of China until that date.<br>^ On June 19<sup>th</sup> the Spanish Ministry of Health has issued a revised death total for Spain. The deaths have been added proportionally to the daily confirmed deaths of Spain until that date.</span><br><br>**Visualization: Cédric Scherer  •  Data: Johns Hopkins University Center for Systems Science and Engineering (CSSE) via datahub.io**')

ggsave(here::here("plots", glue::glue("corona_heat_trend_latest_compact.pdf")),
       width = fig_width - 4.5, height = fig_height + .5, device = cairo_pdf)

## convert pdf to png
setwd(here::here("plots"))
pdf_convert(pdf = here::here("plots", "corona_heat_trend_latest_compact.pdf"), 
            format = "png", dpi = 500)
```


### grey-colored downward trends

```{r static-plot-trend, fig.width = fig_width, fig.height = fig_height + .5}
ggplot(df,
       aes(country,
           yday, 
           group = yday)) +
  geom_tile(aes(color = rel,
                fill = rel),
            size = .01) +
  geom_tile(data = df %>% filter(worse == F),
            aes(fill = rel,
                fill = after_scale(desaturate(fill))),
            size = .03) +
  geom_richtext(data = df %>% filter(yday == latest_day),
                aes(country,
                    21.4,
                    label = lab),
                family = "Overpass Mono",
                size = 3.8,
                fill = NA, 
                label.color = NA,
                hjust = 1,
                vjust = .6) +
  geom_segment(aes(x = n_countries - .5,
                   xend = n_countries - .5,
                   y = 17.3,
                   yend = latest_day + .5),
               color = "grey40",
             size = .2) +
  geom_tile(data = df %>% filter(rel == 1),
            color = "black",
            fill = NA,
            size = .5) +
  geom_text(data = df %>% filter(yday == latest_day),
            aes(country,
                yday,
                label = lab_daily),
            family = "Overpass",
            color = "grey20",
            size = 2.2,
            hjust = .5) +
  geom_text(data = df %>% filter(rel == 1),
            aes(country,
                yday,
                label = lab_daily),
            family = "Overpass",
            fontface = "bold",
            size = 2.2,
            hjust = .5) +
  geom_text(data = df_labs %>% filter(worse == T),
            aes(country,
                latest_day + .8,
                label = country,
                color = rel,
                color = after_scale(darken(color, .15, space = "HLS"))),
            family = "Open Sans",
            fontface = "bold",
            size = 3.7,
            hjust = 0) +
  geom_text(data = df_labs %>% filter(worse == F),
            aes(country,
                latest_day + .8,
                label = country,
                color = rel,
                color = after_scale(desaturate(darken(color, .2, space = "HLS")))),
            family = "Open Sans",
            fontface = "bold",
            size = 3.7,
            hjust = 0) +
  coord_flip(clip = "off") +
  scale_x_discrete(expand = c(.001, 0.01)) +
  scale_y_continuous(expand = c(.001, 0.01),
                     limits = c(17.3, latest_day + 7),
                     sec.axis = dup_axis(),
                     breaks = dates,
                     labels = dates_lab) + 
  rcartocolor::scale_color_carto_c(palette = "PinkYl", 
                                   na.value = darken("#badad0", .1, space = "HLS"),
                                   limits = c(0, 1),
                                   guide = F) +
  rcartocolor::scale_fill_carto_c(palette = "PinkYl", 
                                  na.value = darken("#badad0", .1, space = "HLS"),
                                  name = "COVID-19 death cases relative to each country's highest daily death toll so far",
                                  limits = c(0, 1),
                                  breaks = c(.001, seq(.25, 1, by = .25)),
                                  labels = c("0.1% of daily max", "25% of daily max", 
                                             "50% of daily max", "75% of daily max", 
                                             "Worst day so far")) +
                                  #breaks = c(.01, seq(.1, 1, by = .1)),
                                  #labels = scales::percent_format(accuracy = 1)) +
  guides(fill = guide_colorbar(title.position = "top",
                               title.hjust = .5,
                               label.position = "bottom",
                               label.hjust = .5,
                               barwidth = unit(55, "lines"),
                               barheight = unit(.75, "lines"))) +
  labs(x = NULL, y = NULL, 
       title = "<b style='color:#c93a6e;'>The Worst Days:</b> Which Countries are Currently Experiencing the Highest<br>Number of Confirmed Daily Deaths Due to COVID-19 So Far?",
       caption = '**The visualization shows countries with at least 200 reported deaths due to the corona virus disease (COVID-19).** The color intensity for each day and country is estimated as the<br>number of deaths on this particular day divided by the highest daily death toll so far. The countries are ranked by time since the latest "worst day" and number of reported daily deaths.<br>Days that are better than the day before (i.e. less confirmed daily deaths) are colored in grey to visulize decreasing trends and potential periodicity in the data.<br><br><span style="font-size:11pt">* On April 17<sup>th</sup> 2020, officials in Wuhan, China, revised the city´s coronavirus death toll. The deaths have been added proportionally to the daily confirmed deaths of China until that date.<br>^ On June 19<sup>th</sup> the Spanish Ministry of Health has issued a revised death total for Spain. The deaths have been added proportionally to the daily confirmed deaths of Spain until that date.</span><br><br>**Visualization: Cédric Scherer  •  Data: Johns Hopkins University Center for Systems Science and Engineering (CSSE) via datahub.io**')

ggsave(here::here("plots", glue::glue("corona_heat_trend_latest_grey.pdf")),
       width = fig_width, height = fig_height + .5, device = cairo_pdf)

## convert pdf to png
setwd(here::here("plots"))
pdf_convert(pdf = here::here("plots", "corona_heat_trend_latest_grey.pdf"), 
            format = "png", dpi = 500)
```


***

```{r session-info}
sessionInfo()
```
