---
title: "Corona Worst-Day World Tile Map"
author: "Cedric Scherer"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
Sys.setlocale("LC_TIME", "C")
```


## Setup
  
```{r prep}
library(tidyverse)
library(lubridate)
library(zoo)
library(ggtext)
library(pdftools)
library(showtext)

font_add_google("Open Sans", "Open Sans")
font_add_google("Overpass", "Overpass")
font_add_google("Overpass Mono", "Overpass Mono")

showtext_auto()

theme_set(theme_minimal(base_size = 16, base_family = "Open Sans"))
theme_update(axis.ticks = element_blank(),
             axis.title = element_blank(),
             axis.text = element_blank(),
             panel.grid = element_blank(),
             legend.title = element_text(size = 13, color = "grey40"),
             legend.text = element_text(family = "Overpass", size = 11, color = "grey40"),
             plot.title = element_markdown(family = "Overpass", size = 35, face = "bold",
                                           color = "black", hjust = .5, lineheight = 1.05,
                                           margin = margin(0, 0, 0, 0)),
             plot.caption = element_text(size = 13, color = "grey20", face = "bold", hjust = .5, 
                                         lineheight = 1.05, margin = margin(-5, 0, 0, 0)),
             plot.margin = margin(35, 70, 20, 70))
```


## Data Preparation

```{r data}
## download atest data
df_corona <- readr::read_csv("https://datahub.io/core/covid-19/r/time-series-19-covid-combined.csv")

## deaths per day with clean column names, dates and country names 
df_corona_days <-
  df_corona %>% 
  dplyr::select(
    date = Date,
    country = `Country/Region`,
    state = `Province/State`,
    deaths = Deaths
  ) %>% 
  group_by(country, date) %>% 
  summarize(deaths = sum(deaths, na.rm = T)) %>% 
  group_by(country) %>%
  mutate(
    yday = yday(date),
    day = day(date),
    month = month(date, label = T)
  ) %>% 
  arrange(country, yday) %>% 
  mutate(
    daily = deaths - lag(deaths),
    daily = if_else(is.na(daily), deaths, daily),
    daily = if_else(daily < 0, 0, daily)
  ) %>% 
  ungroup() %>% 
  filter(yday >= min(yday[which(daily > 0)]) - 6) %>% 
  mutate(
    #daily = if_else(daily <= 0, NA_real_, daily),
    country = case_when(
      country == "US" ~ "United States of America",
      country == "Korea, South" ~ "South Korea",
      country == "Bosnia and Herzegovina" ~ "Bosnia & Herzegovina",
      country == "China" ~ "China*",
      country == "Spain" ~ "Spain^",
      country == "Congo (Kinshasa)" ~ "DR Congo",
      country == "Congo (Brazzaville)" ~ "Congo-Brazzaville",
      TRUE ~ country
    ),
    country = str_replace(country, " and ", " & ")
  )

## summary of confirmed deaths worldwide
df_corona_world <-
  df_corona_days %>% 
  group_by(date, yday, day, month) %>% 
  summarize_at(
    vars(c("deaths", "daily")), sum, na.rm = T
  ) %>% 
  filter(daily > 0) %>% 
  mutate(country = "Worldwide")

## add days before first death in China to calculate rolling avg
df_corona_china_zeros <-
  df_corona_days %>% 
  filter(country == "China*") %>% 
  slice(1:6) %>% 
  mutate(
    date = date - 6,
    deaths = 17,
    yday = yday(date),
    day = day(date),
    month = month(date, label = T),
    daily = 0
  )

## fix deaths in Wuhan, China, that were reported late
china_deaths <- 
  df_corona_days %>% 
  filter(country == "China*" & yday == 108) %>% ## April 17th
  pull(daily)

df_corona_china_fix <-
  df_corona_days %>% 
  filter(country == "China*" & yday <= 108) %>% 
  mutate(
    daily = if_else(yday == 108, 0, daily),
    daily = daily + round(daily * china_deaths / sum(daily)),
    daily = if_else(daily == max(daily), daily - 3, daily)
  ) 

## fix deaths in Spain, that were revised later
spain_deaths <- 
  df_corona_days %>% 
  filter(country == "Spain^" & yday == 171) %>% ## June 19th
  pull(daily)

df_corona_spain_fix <-
  df_corona_days %>% 
  filter(country == "Spain^" & yday <= 171) %>% 
  mutate(
    daily = if_else(yday == 171, 0, daily),
    daily = if_else(is.na(daily), 0, daily),
    daily = daily + round(daily * spain_deaths / sum(daily)),
    daily = if_else(daily == max(daily), daily + 5, daily),
    daily = if_else(daily == 0, NA_real_, daily)
  ) 

## calculate rolling average and add label column
df_corona_roll <- 
  df_corona_days %>% 
  filter(
    !(country == "China*" & yday <= 108) &
    !(country == "Spain^" & yday <= 171)
  ) %>% 
  bind_rows(df_corona_world) %>% 
  bind_rows(df_corona_china_zeros) %>% 
  bind_rows(df_corona_china_fix) %>% 
  bind_rows(df_corona_spain_fix) %>% 
  arrange(country, date) %>% 
  group_by(country) %>% 
  mutate(
    #daily = if_else(is.na(daily), 0, daily),
    roll = rollmean(daily, 7, align = "right", fill = NA),
    max = max(roll, na.rm = T),
    rel = roll / max,
    rel = if_else(is.na(rel), 0, rel),
    sum = sum(daily, na.rm = T),
    day_first = min(yday[which(rel > 0)]),
    day_rel = yday - day_first,
    worse = if_else(lag(rel) <= rel, T, F),
    worse = if_else(is.na(worse), T, worse)
  ) %>% 
  filter(day_rel >= 0) %>%   ##yday < max(yday) - 5, 
  mutate(
    day_max = max(yday[which(rel == 1)]),
    rel = if_else(rel < 0, 0, rel)
  ) %>% 
  ungroup()

df_dates <-
  df_corona_roll %>% 
  filter(date %in% c(min(date, na.rm = T),
                     ymd("2020-02-01"),
                     ymd("2020-02-15"),
                     ymd("2020-03-01"),
                     ymd("2020-03-15"),
                     ymd("2020-04-01"),
                     ymd("2020-04-15"),
                     ymd("2020-05-01"),
                     ymd("2020-05-15"),
                     ymd("2020-06-01"),
                     max(date, na.rm = T))) %>% 
  group_by(date, yday) %>% 
  summarize(label = unique(glue::glue("{month(date, label = T)} {day(date)}")))

dates <- df_dates$yday
dates_lab <- df_dates$label

first_day <- min(df_corona_roll$yday)
latest_day <- max(df_corona_roll$yday)
latest_rel <- max(df_corona_roll$day_rel)

fig_width = 17
fig_height = 13

df_world_tile <- 
  readr::read_csv("https://gist.githubusercontent.com/maartenzam/787498bbc07ae06b637447dbd430ea0a/raw/9a9dafafb44d8990f85243a9c7ca349acd3a0d07/worldtilegrid.csv") %>% 
  mutate(
    alpha.2 = if_else(name == "Namibia", "NA", alpha.2),
    name = case_when(
      name == "US" ~ "United States",
      name == "China" ~ "China*",
      name == "Brunei Darussalam" ~ "Brunei",
      name == "Congo" ~ "Congo-Brazzaville",
      name == "Congo (Democratic Republic of the)" ~ "DR Congo",
      name == "Czech Republic" ~ "Czechia",
      name == "Iran (Islamic Republic of)" ~ "Iran",
      name == "Moldova (Republic of)" ~ "Moldova",
      name == "Macedonia" ~ "North Macedonia",
      name == "Russian Federation" ~ "Russia",
      name == "Great Britain and Northern Ireland" ~ "United Kingdom",
      TRUE ~ name
    ),
    country = name
  )
```


## Animation: Worst-Day Global Pattern 

```{r animation-hex-map, fig.width = fig_width, fig.height = fig_height}
for(i in first_day:latest_day) {
  print(i)
  
  ## only countries with more than 50 or more confirmed deaths
  df_corona_tile <- 
    df_corona_roll %>% 
    filter(yday == i) %>%
    full_join(df_world_tile) %>% 
    filter(!is.na(name)) 
  
  p <- 
    df_corona_tile %>% 
    ggplot(aes(x, y, 
               #color = rel, 
               fill = rel)) + 
      geom_tile(color = "white",
                size = .5) +
      geom_text(data = df_corona_tile %>% filter(!is.na(rel)),
                aes(label = alpha.3,
                    color = rel,
                    color = after_scale(colorspace::darken(color, .5, space = "HLS"))), 
                family = "Overpass",
                fontface = "bold") +
      geom_text(data = df_corona_tile %>% filter(is.na(rel)),
                aes(label = alpha.3), 
                family = "Overpass",
                color = "#99c8b9") +
      geom_label(data = df_corona_tile %>% filter(!is.na(date)) %>% summarize(date = unique(date)),
                 aes(25, 1.6, label = date),
                 inherit.aes = F,
                 family = "Overpass Mono",
                 fontface = "bold",
                 color = "grey60",
                 size = 6,
                 label.padding = unit(.8, "lines"),
                 label.r = unit(0, "lines"),
                 label.size = .6) +
      annotate("text", 4.45, 22,
               label = "The color intensity for each day and country is estimated as the 7-day rolling average of\nconfirmed daily deaths divided by the highest average death toll so far. The deaths reported\non April 17 in Wuhan, China, have been added proportionally to the daily deaths until that date.", 
               family = "Overpass",
               color = "grey40",
               size = 3.9,
               lineheight = 1.05) +
      coord_equal(clip = "off") +
      scale_x_continuous(expand = c(.001, .001)) +
      scale_y_reverse() +
      rcartocolor::scale_color_carto_c(palette = "PinkYl", 
                                       na.value = "#f0f7f5",
                                       guide = F) +
      rcartocolor::scale_fill_carto_c(palette = "PinkYl", 
                                      na.value = "#f0f7f5",
                                      name = "Confirmed COVID-19 deaths relative to each country's maximum so far",
                                      limits = c(0, 1),
                                      breaks = c(.001, seq(.25, 1, by = .25)),
                                      labels = c("0.1%", "25%", "50%", "75%", "                                    100% = worst day so far")) +
                                      #breaks = c(.01, seq(.25, 1, by = .25)),
                                      #labels = scales::percent_format(accuracy = 1)) +
      guides(fill = guide_colorbar(direction = "horizontal",
                                   title.position = "top",
                                   title.hjust = .5,
                                   label.position = "bottom",
                                   label.hjust = .5,
                                   barwidth = unit(30, "lines"),
                                   barheight = unit(.6, "lines"))) +
      labs(title = "<b style='color:#c93a6e;'>The Worst Days:</b> Peaks in Confirmed Daily Deaths Due to COVID-19 So Far",
           caption = "Visualization: Cédric Scherer  •  Data: Johns Hopkins University Center for Systems Science and Engineering (CSSE) via datahub.io") +
      theme(legend.position = c(.14, .2))
  
  ggsave(glue::glue(here::here("plots", "series_map", "corona_map_yday_{sprintf('%03d', i)}.pdf")),
         width = fig_width, height = fig_height, device = cairo_pdf)
  
  if(i == latest_day) {
    ggsave(glue::glue(here::here("plots", "series_map", "corona_map_yday_latest.pdf")),
         width = fig_width, height = fig_height, device = cairo_pdf)
  }
}

## convert pdf's to png's
setwd(here::here("plots", "series_map"))
pdfs <- list.files(here::here("plots", "series_map"), pattern = "*.pdf")

for(pdf in pdfs) {
  pdf_convert(pdf = here::here("plots", "series_map", pdf), 
              format = "png", dpi = 200)
}

## convert png's to gif
system("magick.exe -delay 40 *.png -delay 200 *latest_1.png -loop 0 corona_map.gif")

pdf_convert(pdf = here::here("plots", "series_map", "corona_map_yday_latest.pdf"), 
              format = "png", dpi = 750)

## grey-scaled version for "better days"
if(i == latest_day) {
   p +
      geom_tile(data = df_corona_tile %>% filter(worse == F),
               aes(fill = rel, fill = after_scale(colorspace::desaturate(fill))),
               color = "white",
               size = .5) +
      geom_text(data = df_corona_tile %>% filter(worse == F),
                aes(label = alpha.3,
                    color = rel,
                    color = after_scale(colorspace::desaturate(colorspace::darken(color, .5, space = "HLS")))), 
                family = "Overpass",
                fontface = "bold")
  
  ggsave(glue::glue(here::here("plots", "series_map", "corona_map_yday_latest_grey.pdf")),
         width = fig_width, height = fig_height, device = cairo_pdf)
}

pdf_convert(pdf = here::here("plots", "series_map", "corona_map_yday_latest_grey.pdf"), 
              format = "png", dpi = 750)
```


## Plot: Date of First Death

```{r date-first-death-hex-map, fig.width = fig_width - 2, fig.height = fig_height}
df_corona_tile <- 
  df_corona_roll %>% 
  group_by(country) %>% 
  filter(yday == min(yday[which(daily > 1)])) %>%
  ungroup() %>% 
  full_join(df_world_tile) %>% 
  filter(!is.na(name)) %>% 
  mutate(
    text_col = if_else(yday <= latest_day - 10, "A", "B")
  )
  
df_corona_tile %>% 
  ggplot(aes(x, y, 
             fill = yday)) + 
    geom_tile(color = "white",
              size = .5) +
    geom_text(data = df_corona_tile %>% filter(!is.na(day_rel)),
              aes(label = alpha.3,
                  color = text_col), 
              family = "Overpass",
              fontface = "bold") +
    # geom_text(data = df_corona_tile %>% filter(!is.na(day_rel)),
    #             aes(label = alpha.3,
    #                 color = day_rel,
    #                 color = after_scale(colorspace::darken(color, .5, space = "HLS"))), 
    #             family = "Overpass",
    #             fontface = "bold") +
    # geom_text(data = df_corona_tile %>% filter(!is.na(day_rel), day_rel < 25),
    #             aes(label = alpha.3,
    #                 color = day_rel,
    #                 color = after_scale(colorspace::lighten(color, .5, space = "HLS"))), 
    #             family = "Overpass",
    #             fontface = "bold") +
    geom_text(data = df_corona_tile %>% filter(is.na(day_rel)),
                aes(label = alpha.3), 
                family = "Overpass",
                color = "#99c8b9") +
    coord_equal(clip = "off") +
    scale_x_continuous(expand = c(.001, .001)) +
    scale_y_reverse() +
    scale_color_manual(values = c("white", "grey60"), guide = F) +
    scale_fill_viridis_c(option = "magma",
                         na.value = "#f0f7f5",
                         limits = c(NA, max(dates)),
                         name = "",
                         breaks = dates,
                         labels = dates_lab) +
    guides(fill = guide_colorbar(direction = "horizontal",
                                 title.position = "top",
                                 title.hjust = .5,
                                 label.position = "top",
                                 label.hjust = .5,
                                 barwidth = unit(54, "lines"),
                                 barheight = unit(.75, "lines"))) +
    labs(title = "Date of the First Confirmed Death Due to COVID-19",
         caption = "Visualization: Cédric Scherer  •  Data: Johns Hopkins University Center for Systems Science and Engineering (CSSE) via datahub.io") +
    theme(legend.position = "top",
          legend.text = element_text(family = "Overpass", size = 15))

setwd(here::here("plots"))
ggsave(glue::glue(here::here("plots", "corona_map_date.pdf")),
       width = fig_width - 2, height = fig_height, device = cairo_pdf)

pdf_convert(pdf = here::here("plots", "corona_map_date.pdf"), 
              format = "png", dpi = 750)
```

***

```{r session-info}
sessionInfo()
```
